#미로의 출구 찾기
전제

s = 시작점

e = 출구


-1 = 지나온 길 / 음수로 표시

0 = 내가 갈 수 있는 위치

1 = 벽

# DFS

깊이 우선 탐색

(반복)

현재 위치에 방문한 표시(-1)

현재 위치가 출구이면 종료

아닌 경우, 상하좌우 순서로 방향 탐색 (범위 내인지, 길(0)인지)

상하좌우(x,y-1) (x,y+1) (x-1,y) (x+1,y)

-> 충족 시 이동(stack push) / 불충족 시(0이 없으면) 이전 위치(-1)탐색하여 스택에 저장 돌아감(stack pop)

In [1]:
map = [[1,1,1,1,1,1],
       ['s',0,0,0,0,1],
       [1,0,1,0,1,1,],
       [1,1,1,0,0,'e'],
       [1,1,1,0,1,1],
       [1,1,1,1,1,1]]

In [2]:
# stack 활용
class DFS:
  def __init__ (self,map,start,exit):
    self.map = map
    self.start = start #start,exit는 tuple(x,y)로 받음
    self.exit = exit
  
  def isValidPos (self,x,y): # 미로 범위 확인
    if x < 0 or y < 0 or x >= len(self.map) or y>= len(self.map):
      return False
    else:
      return True

  def udlr (self, x, y, num): # 길 탐색. num은 길의 유형
    pos = []
    if self.isValidPos (x,y-1) == True and self.map[y-1][x] == num: #상
        pos = [x, y-1]
    elif self.isValidPos (x,y+1) == True  and self.map[y+1][x] == num: # 하
        pos = [x, y+1]    
    elif self.isValidPos (x+1,y) == True  and self.map[y][x+1] == num: # 좌
        pos = [x+1, y]
    elif self.isValidPos (x-1,y) == True  and self.map[y][x-1] == num: # 우
        pos = [x-1, y]
        
    else: return 0
    return pos # stack에 저장할 위치 값
  
  def sol (self):
    stack = []

    stack.append(list(self.start)) # stack에 입구 위치 list[x,y] 추가, 
    ex, ey = self.exit
    self.map[ey][ex] = 0

    while len(stack) != 0: # stack이 빌 때까지 반복 
      here = stack.pop(-1) # 현재 위치 = 마지막 저장위치 / 스택에서 지움
      x, y = here 
      
      self.map[y][x] = -1 # 현재 위치를 지나온 길로 표시

      if here == list(self.exit):
        print('탐색 성공') # 현재 위치가 출구일 때
        stack = [] # stack을 비워 while문 반복 종료
        return self.map

      else:
        s = self.udlr(x,y,0) 
        if s != 0:# 갈 수 있는 길이 있을 때
          stack.append(s) # 미로 범위 내에 있고 가지 않은 길인 경우. stack에 저장
  
        else:# 0인 길이 없는 경우. 되돌아 나가야 할 때  
          s = self.udlr(x,y,-1) # 들어온 길을 되돌아 나가기 때문에 s값이 0일 경우는 없음. 
          stack.append(s) # 지나온 길인 -1 값을 가진 [x,y] 값 추가 
          self.map[y][x] == 1 
          continue

In [3]:
import pandas as pd
import numpy as np

In [4]:
map = [[1,1,1,1,1,1],
       ['s',0,0,0,0,1],
       [1,0,1,0,1,1,],
       [1,1,1,0,0,'e'],
       [1,1,1,0,1,1],
       [1,1,1,1,1,1]]
org_map = np.array(map)
pd.DataFrame(org_map)

   0  1  2  3  4  5
0  1  1  1  1  1  1
1  s  0  0  0  0  1
2  1  0  1  0  1  1
3  1  1  1  0  0  e
4  1  1  1  0  1  1
5  1  1  1  1  1  1

In [5]:
dfs = DFS(map,(0,1),(5,3))
dfs_map = np.array(dfs.sol())
pd.DataFrame(dfs_map)

탐색 성공

   0  1  2  3  4  5
0  1  1  1  1  1  1
1 -1 -1 -1 -1  0  1
2  1 -1  1 -1  1  1
3  1  1  1 -1 -1 -1
4  1  1  1 -1  1  1
5  1  1  1  1  1  1

# BFS

너비 우선 탐색

시작점에서 가까운 노드부터 차례대로 그래프의 모든 노드를 탐색